services:
#  database:
#    container_name: database
#    image: postgres:latest
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#    volumes:
#      - database:/var/lib/postgresql/data
#    ports:
#      - "5435:5432"
#    restart: unless-stopped
  filestorage:
    container_name: filestorage
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_admin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - filestorage:/data
    command: server --console-address ":9001" /data/
    restart: unless-stopped
volumes:
  database:
    driver: local
  filestorage:
    driver: local