spring:
  datasource:
    url: jdbc:h2:mem:shop
    username: admin
    password: admin
minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:minio_admin}
  secret-key: ${MINIO_SECRET_KEY:minio_admin}
  products-bucket-name: ${PRODUCTS_BUCKET_NAME:products}