spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: postgres
minio:
  endpoint: http://localhost:9000
  access-key: minio_admin
  secret-key: 8e8271e6-8378-4f77-a748-d080b9a25599