spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: postgres
minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:minio_admin}
  secret-key: ${MINIO_SECRET_KEY:minio_admin}
  products-bucket-name: ${PRODUCTS_BUCKET_NAME:products}