server:
  port: ${PORT:8085}
  servlet:
    context-path: ${CONTEXT_PATH:/api}
spring:
  application:
    name: ${NAME:shop}
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
app:
  percents:
    fee: 10
    bonus: 5
  jwt:
    prefix: "Bearer "
    header: Authorization
    secret: NDI2MTY1NkM2NDc1NkU2N19jYXJfc2hvcF9hcHA
    access-token-expiration: 3600000
    refresh-token-expiration: 86400000